import React, { useState, useEffect } from "react";
import { useSeo } from "../utils/seo";
import { useLoadingStore } from "../store/loading";

import { useTina } from "tinacms/dist/react";
import Hero from "../components/Hero";
import Services from "../components/Services";
import LoadingSpinner from "../components/LoadingSpinner";

import About from "../components/About";
import WhyChoose from "../components/WhyChoose";
import Process from "../components/Process";
import Testimonials from "../components/Testimonials";
import FAQ from "../components/FAQ";
import CTA from "../components/CTA";
import Contact from "../components/Contact";
// We import the client. Note: This file is generated by 'tinacms dev' or 'tinacms build'
// If you haven't run that yet, this import might show an error in your editor.
import { client } from "../../tina/__generated__/client";

const HomeContent = ({ initialData }) => {
  const { data: tinaData } = useTina({
    query: initialData.query,
    variables: initialData.variables || {},
    data: initialData.data || {},
  });

  useSeo(tinaData?.page);

  const setPageLoaded = useLoadingStore((state) => state.setPageLoaded);

  useEffect(() => {
    if (tinaData?.page) {
      setPageLoaded(true);
    }
  }, [tinaData, setPageLoaded]);

  if (!tinaData?.page) {
    return <LoadingSpinner />;
  }

  const { blocks } = tinaData.page;

  return (
    <div>
      {blocks?.map((block, i) => {
        switch (block.__typename) {
          case "PageBlocksHero":
            return <Hero key={i} data={block} />;
          case "PageBlocksAbout":
            return <About key={i} data={block} />;
          case "PageBlocksServices":
            return <Services key={i} previewMode={true} data={block} />;
          case "PageBlocksCta":
            return <CTA key={i} data={block} />;
          case "PageBlocksWhyChoose":
            return <WhyChoose key={i} data={block} />;
          case "PageBlocksProcess":
            return <Process key={i} data={block} />;
          case "PageBlocksTestimonials":
            return <Testimonials key={i} data={block} />;
          case "PageBlocksFaq":
            return <FAQ key={i} data={block} />;
          case "PageBlocksContact":
            return <Contact key={i} data={block} />;
          default:
            return null;
        }
      })}
    </div>
  );
};

const Home = () => {
  const [data, setData] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await client.queries.page({ relativePath: "home.md" });
        setData(res);
      } catch (e) {
        console.error("Error fetching Tina data:", e);
      }
    };
    fetchData();
  }, []);

  if (!data) {
    return <LoadingSpinner />;
  }

  return <HomeContent initialData={data} />;
};

export default Home;
